### ISSUE TITLE
Running build tool under linux

### ISSUE THREAD

**Issue by expose** [greatyao/aamlibrary#2]
I'm using aamlibrary on Ubuntu 12.04.5 and I can't finish building amf file. When running
./build -t 0 -p 3 ./training jpg pts haarcascade_frontalface_alt2.xml my.amf
 I get the following error:
`OpenCV Error: One of arguments' values is out of range () in cvSubdiv2DLocate, file /home/miloszm/aam/opencv-2.4.9/modules/legacy/src/subdiv2.cpp, line 221 terminate called after throwing an instance of 'cv::Exception'                              
  what():  /home/miloszm/aam/opencv-2.4.9/modules/legacy/src/subdiv2.cpp:221: error: (-211) in function cvSubdiv2DLocate`
As a training set I'm using data from: https://github.com/shogun-toolbox/shogun-data
Any idea what might be wrong?

**Comment by greatyao** [comment]
@expose goto https://github.com/greatyao/asmlibrary/wiki/ASMLibrary#Guide for building details
I find that your pts files is not compatible with Cootes's pts files
see http://personalpages.manchester.ac.uk/staff/timothy.f.cootes/tfc_software.html for pts format

**Comment by expose** [comment]
New training set worked great, thanks a lot.
