### ISSUE TITLE
Some error ：'char' followed by 'char' is illegal when I build it in VS2013 under windows

### ISSUE THREAD

**Issue by Ocxs** [greatyao/aamlibrary#3]
I open AAMLibrary.sln with MS Visual Studio 2013，and When I rebuild it ，error happened.

![image](https://cloud.githubusercontent.com/assets/11175797/8870315/94396224-321f-11e5-9e5d-e2789337e8a9.png)
![image](https://cloud.githubusercontent.com/assets/11175797/8870318/9a63263a-321f-11e5-8900-4e1b547e697b.png)

Can you help me ? Thank you in advance!

**Comment by hritt** [comment]
I think you have added "#include < windows.h >". Try to add "#include < windows.h >" to first line in AAM_Util.cpp.

**Comment by Ocxs** [comment]
@hritt Yes，you're right!
And before you answer this question, I fixed it with another way .
I use

``` cpp
typedef unsigned char byte;
```

to replace 

``` cpp
#ifndef byte
#define byte unsigned char
#endif
```

Finally, I think your solution is better. Thank you! :+1:

**Comment by Ocxs** [comment]
@hritt 看了你的主页，看您在南京工作，我就直接用中文了，我用`vs2013`导入这个项目的时候，现在已经改差不多没有错误了 ，然后我设置`aambuilding`为启动项目，点击”本地`windows`调试器“，控制台就一闪而过，没有了，我看`train.cpp`里的参数是需要输入的，然后我把那些东西注释了，参数都在代码里写好，然后家断点调试的时候，发现根本就没有进`main`函数里执行，之前遇到一个错误就是”无法启动程序，`D:\code\1downLoad\aamlibrary-master\msvc\bin\aambuilding.exe`系统找不到指定的文件，”，然后我把他`bin`文件夹下的`build.exe`改为`aambuilding.exe`放在这个目录`D:\code\1downLoad\aamlibrary-master\msvc\bin\aambuilding.exe`下面,然后就没有那个错，但是就出现我刚才说的，一闪而过的情况，不知道怎么回事，请问怎么解决呢？

**Comment by Ocxs** [comment]
@hritt  问题已经解决了，我将他源代码导出来，自己重新新建一个之后调通了，问题是在fit阶段，对视频进行操作的时候，操作一段时间后会中断，还没找出原因，望赐教！
